openapi: 3.0.0
info:
  title: LocalFindr API
  description: A location-based API for managing and discovering places
  version: 1.0.0

servers:
  - url: http://localhost:5000

paths:
  /api/places:
    post:
      summary: Create a new place
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlaceInput'
      responses:
        '201':
          description: Created
    get:
      summary: Get all places
      responses:
        '200':
          description: OK

  /api/places/{id}:
    get:
      summary: Get place by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
    put:
      summary: Update place by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlaceInput'
      responses:
        '200':
          description: Updated
    delete:
      summary: Delete place by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Deleted

  /api/places/nearby:
    get:
      summary: Get nearby places by category
      parameters:
        - in: query
          name: lat
          schema:
            type: number
          required: true
        - in: query
          name: lng
          schema:
            type: number
          required: true
        - in: query
          name: category
          schema:
            type: string
          required: true
        - in: query
          name: radius
          schema:
            type: number
          required: true
      responses:
        '200':
          description: OK

  /api/places/{id}/distance:
    get:
      summary: Get distance from user location to place
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: query
          name: lat
          schema:
            type: number
          required: true
        - in: query
          name: lng
          schema:
            type: number
          required: true
      responses:
        '200':
          description: Distance returned

  /api/google/search:
    get:
      summary: Search nearby Google Places
      parameters:
        - in: query
          name: lat
          required: true
          schema:
            type: number
        - in: query
          name: lng
          required: true
          schema:
            type: number
        - in: query
          name: type
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Google Places found

  /api/google/favorites:
    post:
      summary: Add a favorite Google place
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FavoriteInput'
      responses:
        '200':
          description: Favorite added

  /api/google/favorites/{userId}:
    get:
      summary: Get user’s favorite places
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Favorite places

components:
  schemas:
    PlaceInput:
      type: object
      properties:
        name:
          type: string
        category:
          type: string
        location:
          type: object
          properties:
            type:
              type: string
              enum: [Point]
            coordinates:
              type: array
              items:
                type: number

    FavoriteInput:
      type: object
      properties:
        userId:
          type: string
        placeId:
          type: string
        name:
          type: string
        address:
          type: string
